CONFIG_I2C=y
CONFIG_BT=y
CONFIG_BT_EXT_ADV=y
CONFIG_DK_LIBRARY=y
CONFIG_ADC=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_TIMESLICING=y
CONFIG_TIMESLICE_SIZE=10
CONFIG_UART_ASYNC_API=y
CONFIG_UART_CONSOLE=y
CONFIG_MULTITHREADING=y
#Custom config 
CONFIG_BT_DEVICE_NAME="Meteo_Station_Beacon"
CONFIG_BME_SENSOR_ENABLE=y
CONFIG_CJMCU_SENSOR_ENABLE=y
CONFIG_MH_RD_SENSOR_ENABLE=y
CONFIG_ML_SENSOR_ENABLE=y
CONFIG_UART_REPORT_ENABLE=y